Update deploy-to-production.yml

diff --git a/.github/workflows/deploy-to-production.yml b/.github/workflows/deploy-to-production.yml
--- a/.github/workflows/deploy-to-production.yml
+++ b/.github/workflows/deploy-to-production.yml
@@ -18,6 +18,10 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           tags=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://ghcr.io/v2/actions/gha-runner-scale-set-controller/tags/list | jq -r '.tags[]')
+          if [ -z "$tags" ]; then
+            echo "No tags found or authentication failed"
+            exit 1
+          fi
           latest_tag=$(echo "$tags" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
           echo "Latest tag: $latest_tag"
           echo "::set-output name=latest_tag::$latest_tag"
