Update deploy-to-production.yml

diff --git a/.github/workflows/deploy-to-production.yml b/.github/workflows/deploy-to-production.yml
--- a/.github/workflows/deploy-to-production.yml
+++ b/.github/workflows/deploy-to-production.yml
@@ -47,4 +47,9 @@ jobs:
                 fi
                 
                 echo "------Processing: $acr_image_name ------"
+              } || {
+                  echo "An error occurred while processing: Error: $?"
+                  continue
+              }
+          done                
                
